# Generated by Django 5.1.7 on 2025-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth_app", "0002_auto_20250302_2157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
