# Generated by Django 5.1.7 on 2025-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth_app", "0005_alter_business_id_alter_businessdata_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Retail", "Retail"),
                    ("Service", "Service"),
                    ("Manufacturing", "Manufacturing"),
                    ("Technology", "Technology"),
                    ("Food", "Food & Beverage"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
